// templates/ui/solid/files/src/components/Badge.tsx
import { splitProps, type JSX } from 'solid-js'

type Props = JSX.HTMLAttributes<HTMLSpanElement> & {
  variant?: 'default' | 'accent' | 'success'
  dot?: boolean
}

export function Badge(props: Props) {
  const [local, rest] = splitProps(props, ['variant', 'dot', 'class'])

  const classes = () =>
    ['badge', local.variant && local.variant !== 'default' && `badge-${local.variant}`, local.dot && 'badge-dot', local.class]
      .filter(Boolean)
      .join(' ')

  return <span class={classes()} {...rest} />
}

// templates/ui/react/files/src/components/ui/badge.tsx
import type { HTMLAttributes } from 'react'

type Props = HTMLAttributes<HTMLSpanElement> & {
  variant?: 'default' | 'accent' | 'success'
  dot?: boolean
}

export function Badge({ variant = 'default', dot = false, className, ...props }: Props) {
  const classes = ['badge', variant !== 'default' && `badge-${variant}`, dot && 'badge-dot', className].filter(Boolean).join(' ')

  return <span className={classes} {...props} />
}
