// templates/ui/solid/files/src/components/Button.tsx
import { splitProps, type JSX } from 'solid-js'

type Props = JSX.ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: 'default' | 'outline' | 'ghost'
  size?: 'default' | 'sm' | 'icon'
}

export function Button(props: Props) {
  const [local, rest] = splitProps(props, ['variant', 'size', 'class'])

  const classes = () =>
    ['btn', `btn-${local.variant ?? 'default'}`, local.size && local.size !== 'default' && `btn-${local.size}`, local.class]
      .filter(Boolean)
      .join(' ')

  return <button type="button" class={classes()} {...rest} />
}

// templates/ui/react/files/src/components/ui/button.tsx
import type { ButtonHTMLAttributes } from 'react'

type Props = ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: 'default' | 'outline' | 'ghost'
  size?: 'default' | 'sm' | 'icon'
}

export function Button({ variant = 'default', size = 'default', className, ...props }: Props) {
  const classes = ['btn', `btn-${variant}`, size !== 'default' && `btn-${size}`, className].filter(Boolean).join(' ')

  return <button type="button" className={classes} {...props} />
}
